# Generated by Django 3.0.1 on 2020-01-13 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200113_1835'),
        ('posts', '0002_auto_20200113_1845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='Profile',
            new_name='profile',
        ),
        migrations.AlterField(
            model_name='posts',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profile'),
        ),
    ]
